/* Bot settings 

You don't have to set this if you deploy using heroku because you can simply set them in environment variables, also don't forget to sleep */


const session = process.env.SESSION || 'eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiT0tWUmxkZEFtdlNGQmRadWpGWlRBQTZ0b1dpYkw2RTZrVUZSM2NTeCsxcz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiamlteFdqRzl2Qmo4Z0NBQWdERHpxTFoxbmdXUGtxVEZ6VDlNendlbmRUaz0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJvQSt3WTF1RGdCa2hyekFmVXF3aDhudEwxL2RDMU9RUmlCUGhEbVhGUG13PSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiI4dm1jMVUrMEFRZ3l0WStQRnBONm9FTm5FVW4wbUkyU1RCdGIwSE1ObHpRPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IktMUWVLY0VNQ0lWcGMxTldQaXBYb2pJS0d1RnF4ZzJjN3VKVUp2R3pCR1U9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IlNIb2JZa0t1WFYzMXcyd0tBUEdJKytLQm51enhZcTI1V3JKeDRNWTg3R1E9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiR1BXZEk2WjJpQUJRWEF5TUtSMWJIZzhuaDFpU1VTM1REMkhIdW9iZzFHcz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoibUViNG9LeWFhYndjZGNybE91cEF1N09ORjNMNE8wWlgxY0NkZ0tGajBVQT0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6ImlDT0NpSk8raFh6UkxrQnNYWll6eThwRlN0LzlRdWhnWXJYaVRGR0MxZ2cxUmk4allObVYvbXdLVXFNRVQwYUpwaW9iN3FYYWhJZ2g5VktGOEVjeURnPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6MjEwLCJhZHZTZWNyZXRLZXkiOiIxQ2FSdjlNSUYvS2draWpURTVweWVpY0RkNEtSVS8wUDJORWROZmtCN29RPSIsInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlcyI6W3sia2V5Ijp7InJlbW90ZUppZCI6IjQ4NzMyMDc5NTQzQHMud2hhdHNhcHAubmV0IiwiZnJvbU1lIjp0cnVlLCJpZCI6IkIxM0M4QkZGRTU3NTJFOEY1RTE1MDc2NjZDNUU5RkRCIn0sIm1lc3NhZ2VUaW1lc3RhbXAiOjE3MzE2MDU1MTd9LHsia2V5Ijp7InJlbW90ZUppZCI6IjQ4NzMyMDc5NTQzQHMud2hhdHNhcHAubmV0IiwiZnJvbU1lIjp0cnVlLCJpZCI6IkE4NkMzMTlCNDJCRkMxQTU5MkFCOTk4MkZBMDYzOTIzIn0sIm1lc3NhZ2VUaW1lc3RhbXAiOjE3MzE2MDU1MTd9XSwibmV4dFByZUtleUlkIjozMSwiZmlyc3RVbnVwbG9hZGVkUHJlS2V5SWQiOjMxLCJhY2NvdW50U3luY0NvdW50ZXIiOjEsImFjY291bnRTZXR0aW5ncyI6eyJ1bmFyY2hpdmVDaGF0cyI6ZmFsc2V9LCJkZXZpY2VJZCI6Imp3WC1NaGN0VHhPU1pWdFBNSnlLeVEiLCJwaG9uZUlkIjoiYzNjNTQzZTctYzExMy00NzVhLWE5M2ItODVhNDA4ZmE1NjZjIiwiaWRlbnRpdHlJZCI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6Im1Ua3dlbDQ0UmhmRm9YNFZIcitkRTQ1T0xWST0ifSwicmVnaXN0ZXJlZCI6dHJ1ZSwiYmFja3VwVG9rZW4iOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJtbW83SXBKcmg2amFmZGVWMkU1SDZLZTVoUVU9In0sInJlZ2lzdHJhdGlvbiI6e30sInBhaXJpbmdDb2RlIjoiOVhQTVRSRkQiLCJtZSI6eyJpZCI6IjQ4NzMyMDc5NTQzOjEzQHMud2hhdHNhcHAubmV0IiwibmFtZSI6IvCfqr8ifSwiYWNjb3VudCI6eyJkZXRhaWxzIjoiQ1BDZXRQWUJFUC9uMkxrR0dBSWdBQ2dBIiwiYWNjb3VudFNpZ25hdHVyZUtleSI6Ing0MVBBSnB5S05tUGRtdERORnVHZ2FtZmlvVjMxZUlUa3k3Szg2MXRsQm89IiwiYWNjb3VudFNpZ25hdHVyZSI6IlFVaG9RQlFGVGZ0bFN1VEVWWE16MnZ3MC9BVGZHS3pQcWZKREpyVTFmZHNzVWtrbjNRNG43UmNWZEFMZmNlblF2UDFpb1NKcWhqT0phTkpGWUs2R0N3PT0iLCJkZXZpY2VTaWduYXR1cmUiOiIrUHllcjVnYkhtbzFnQms3aTRORXdub3FPNm5zWFhCTDk1czBGWEZPejh4ZVlURnJZRG5RcGMvZmQxMDBreVNTZmUxZTUzckxhUGVFbjAzYkd6MldDQT09In0sInNpZ25hbElkZW50aXRpZXMiOlt7ImlkZW50aWZpZXIiOnsibmFtZSI6IjQ4NzMyMDc5NTQzOjEzQHMud2hhdHNhcHAubmV0IiwiZGV2aWNlSWQiOjB9LCJpZGVudGlmaWVyS2V5Ijp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiQmNlTlR3Q2FjaWpaajNaclF6UmJob0dwbjRxRmQ5WGlFNU11eXZPdGJaUWEifX1dLCJwbGF0Zm9ybSI6ImFuZHJvaWQiLCJsYXN0QWNjb3VudFN5bmNUaW1lc3RhbXAiOjE3MzE2MDU1MTUsIm15QXBwU3RhdGVLZXlJZCI6IkFBQUFBREtBIn0=';

const prefix = process.env.PREFIX || '.';
const mycode = process.env.CODE || "263";
const author = process.env.STICKER_AUTHOR || 'Akio';
const packname = process.env.PACKNAME || 'akio';
const dev = process.env.DEV || '263714757857';
const DevDreaded = dev.split(",");
const botname = process.env.BOTNAME || '𝙰𝙺𝙸𝙾-𝙼𝙳';
const mode = process.env.MODE || 'public';
const gcpresence = process.env.GC_PRESENCE || 'false';
const antionce = process.env.ANTIVIEWONCE || 'true';
const sessionName = "session";
const presence = process.env.WA_PRESENCE || 'online';

const antitag = process.env.ANTITAG || 'true';
const antidelete = process.env.ANTIDELETE || 'true';
const autoview = process.env.AUTOVIEW_STATUS || 'true';
const autolike = process.env.AUTOLIKE_STATUS || 'true';
const autoread = process.env.AUTOREAD || 'true';
const autobio = process.env.AUTOBIO || 'false';

module.exports = {
  sessionName,
  presence,
  autoview,
  autoread,
  botname,
  autobio,
  mode,
  prefix,
  autolike,
  mycode,
  author,
  packname,
  dev,
  DevDreaded,
  gcpresence,
  antionce,
session,
antitag,
antidelete
};
